# If you see this, run `rustup self update` to get rustup 1.23 or newer.

# NOTE: above comment is for older `rustup` (before TOML support was added),
# which will treat the first line as the toolchain name, and therefore show it
# to the user in the error, instead of "error: invalid channel name '[toolchain]'".

[toolchain]
# Make sure to check the build status before changing this
# https://rust-lang.github.io/rustup-components-history/
channel = "nightly-2021-09-30"
# components = ["clippy", "rustfmt"]
